---
version: "0.1"
globalTimeout: 90
testSuiteTimeout: 90
testSuiteStep: 90
runson: mac
autosplit: true
retryOnFailure: true
maxRetries: 5
concurrency: 15
pre:
  - mvn compile
  - mvn versions:display-dependency-updates
testDiscovery:
  type: raw
  mode: static
  command: grep --with-filename 'def' src/test/groovy/Spec/*.groovy | sed 's/\.groovy\(.*\)def /#/g' | sed -e 's/.*\/\(.*\)(.*/\1/'
testRunnerCommand: ./run.sh $test #mac
# testRunnerCommand: sh run.sh $test #win
